In [5]:
import numpy as np

In [7]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
# Get a specific element [r, c] r is row | c is column
# Let's get 13 from the array above.
a[1, 5] 

13

In [9]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [12]:
# Getting a little more fancy with Numpy. [startindex:endindex:stepsize]
# Example: lets get every element in between 2 and 6
a[0, 1:6:2] #or
a[0, 1:-1:2]

array([2, 4, 6])

In [15]:
# Example: Let's change out the 13 in array to 20.
a[1,5] = 20
print(a)

# if I wanted to replace the [3, 10] column to have all 5's
a[:,2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [17]:
# 3D Arrray Example

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Get specific element (work outside in) 
# Example: Let's get the 4
b[0,1,1]

4

In [19]:
# Another Example
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [22]:
# replacing
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
