In [1]:
# Import the Numpy library
import numpy as np

In [2]:
# if it didn't work then you will have to pip install the library

In [14]:
# One dimensional array
a = np.array([1,2,3], dtype='int32') # its always good to specify the data type here.
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get Dimension of Array
a.ndim

1

In [7]:
b.ndim

2

In [8]:
# Get Shape
a.shape # Should show three rows and no columns

(3,)

In [9]:
b.shape # Should show two rows and three columns

(2, 3)

In [10]:
# Get Type
a.dtype
b.dtype

dtype('float64')

In [11]:
a.dtype

dtype('int32')

In [12]:
# Get Size
a.itemsize

4

In [13]:
# Get total size
a.size

3