In [5]:
import numpy as np

In [13]:
# All 0s matrix | All we need to do is specify a shape.
np.zeros(5) # one dim


array([0., 0., 0., 0., 0.])

In [14]:
# You can also create a complex shape
np.zeros((2,2)) # 2D

array([[0., 0.],
       [0., 0.]])

In [15]:
np.zeros((2,2,2)) #3D

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [16]:
np.zeros((2,3,2,2)) #4D

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [18]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [19]:
# Any other number
np.full((2,2), 99)

array([[5, 5],
       [5, 5]])

In [24]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.57372295, 0.2161108 ],
       [0.42736566, 0.57951745],
       [0.15788691, 0.55487857],
       [0.28354413, 0.72296278]])

In [29]:
# Random Integer values
np.random.randint(7, size=(3,3))

array([[6, 5, 2],
       [0, 5, 4],
       [1, 1, 4]])

In [30]:
# identity matrix
# usually a square matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# Repeating an array

arr = np.array([1,2,3])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]
