In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2

array([2, 4, 6, 8])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [14]:
a +=2 

In [11]:
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [15]:
a ** 2

array([ 49,  64,  81, 100], dtype=int32)

In [16]:
# Take the sin
np.cos(a)

array([ 0.75390225, -0.14550003, -0.91113026, -0.83907153])

#### Linear Algebra ####

In [20]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b) # To multiply different matrixes

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [21]:
# Find the determinant

c = np.identity(3) 
np.linalg.det(c)

1.0

### For more on linear algebra: https://numpy.org/doc/stable/reference/routines.linalg.html

In [22]:
# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics ###

In [23]:
stats = np.array(([1,2,3], [4,5,6]))
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.min(stats, axis=0)

array([1, 2, 3])

In [26]:
np.max(stats, axis=1)

array([3, 6])

In [27]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing Arrays

In [34]:
before = np.array(([1,2,3,4], [5,6,7,8]))
print(before)

after = before.reshape((2,2,2))
print(after)

# When you get an error it's typically because it can't fit the shape of the maxtrix you're trying to make.

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
np.vstack([v1,v2, v1, v2]) # you can add more arrarys if you like to stack vertically.

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
# Horizontal Stack
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])